version: "3.8"

services:
  sns-db:
    image: mysql:8
    env_file:
      - .env
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - sns-db-data:/var/lib/mysql:rw
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:rw
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d:rw
    ports:
      - ${EXTERNAL_MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - mtic-network

  mtic-sns:
    env_file:
      - .env
    depends_on:
      - sns-db
    build: .
    restart: unless-stopped
    environment:
      - MYSQL_HOST=sns-db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${EXTERNAL_SERVER_PORT}:${PORT}
    volumes:
      - '.:/usr/src/api' # Dockerfile의 WORKDIR와 맞추기
      - '/usr/src/api/node_modules' # 핫 리로드 성능 개선
    networks:
      - mtic-network

volumes:
  sns-db-data:

networks:
  mtic-network:
    external: true